---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-22-04
    image: ubuntu:22.04
    pre_build_image: true
    privileged: true
    command: /bin/bash -c "while true; do sleep 30; done"
  - name: ubuntu-20-04
    image: ubuntu:20.04
    pre_build_image: true
    privileged: true
    command: /bin/bash -c "while true; do sleep 30; done"
  - name: oraclelinux-8
    image: oraclelinux:8
    pre_build_image: true
    privileged: true
    command: /bin/bash -c "while true; do sleep 30; done"
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible
