[tox]
minversion = 3.0
envlist = py3-molecule
skipsdist = true

[testenv]
deps =
    molecule
    molecule-docker
    ansible
    docker
commands =
    molecule test --scenario-name default

[testenv:debug]
commands =
    molecule test --scenario-name default -vvv

[testenv:oracle]
commands =
    molecule test --scenario-name oracle
